name: NovaLib
version: ${project.version}
description: An advanced API and Library for all of my plugins and more.
author: Shades161 (NovaFox161)
website: http://www.novamaday.com/plugins/novalib

main: com.novamaday.novalib.plugin.bungee.NovaLib