name: NovaLib
version: ${project.version}
description: An advanced API and Library for our plugins and so much more!
author: DreamExposure
authors: [NovaFox161]
website: https://www.dreamexposure.org/plugins/novalib

api-version: 1.13

softdepend: [Vault, PerWorldChatPlus]

main: com.novamaday.novalib.plugin.bukkit.NovaLib